pull_request_rules:
- name: Automatically merge Scala Steward PRs on CI success
  conditions:
  - author=scala-steward
  - body~=labels:.*semver-patch.*
  - status-success="Build and Test (ubuntu-latest, 2.12.13, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 2.12.14, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 2.12.15, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 2.13.5, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 2.13.6, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 2.13.7, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.0.0, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.0.1, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.0.2, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.1.0-RC2, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.1.0-RC3, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.1.0, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.1.1-RC1, graalvm-ce-java11@20.3.0)"
  - status-success="Build and Test (ubuntu-latest, 3.1.1-RC2, graalvm-ce-java11@20.3.0)"
  actions:
    merge:
      method: merge
