pull_request_rules:
- name: Automatically merge Scala Steward PRs on CI success
  conditions:
  - author=scala-steward
  - body~=labels:.*semver-patch.*
  - status-success="Build and Test (ubuntu-latest, 2.12.15, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.12.17, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.12.18, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.12.19, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.10, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.11, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.12, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.13, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.14, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.1.3, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.2.2, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.3.0-RC6, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.3.0, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.3.1-RC1, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.3.1, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.3.2-RC1, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.3.3, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.4.0-RC1, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.4.0, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.4.1-RC1, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.4.1, temurin@8)"
  actions:
    merge:
      method: merge
