pull_request_rules:
- name: Automatically merge Scala Steward PRs on CI success
  conditions:
  - author=scala-steward
  - body~=labels:.*semver-patch.*
  - status-success="Build and Test (ubuntu-latest, 2.12.14, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.12.15, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.12.17, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.8, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.9, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 2.13.10, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.0.2, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.1.3, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.2.2, temurin@8)"
  - status-success="Build and Test (ubuntu-latest, 3.3.0-RC6, temurin@8)"
  actions:
    merge:
      method: merge
