pull_request_rules:
- name: Automatically merge Scala Steward PRs on CI success
  conditions:
  - author=scala-steward
  - body~=labels:.*semver-patch.*
  - status-success="Build and Test (ubuntu-22.04, 2.12.18, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 2.12.19, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 2.12.20, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 2.13.12, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 2.13.13, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 2.13.14, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 2.13.15, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 2.13.16, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.3.0, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.3.1, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.3.3, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.3.4, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.4.0, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.4.1, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.4.2, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.4.3, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.5.0, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.5.1, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.5.2, temurin@8)"
  - status-success="Build and Test (ubuntu-22.04, 3.6.2, temurin@8)"
  actions:
    merge:
      method: merge
