pull_request_rules:
- name: Automatically merge Scala Steward PRs on CI success
  conditions:
  - author=scala-steward
  - body~=labels:.*semver-patch.*
  - status-success="Build and Test (ubuntu-latest, 2.12.13, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 2.12.14, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 2.12.15, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 2.12.17, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 2.13.5, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 2.13.6, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 2.13.7, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 2.13.8, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.0.0, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.0.1, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.0.2, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.1.0, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.1.1, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.1.2, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.1.3, JavaSpec(Temurin,8))"
  - status-success="Build and Test (ubuntu-latest, 3.2.0, JavaSpec(Temurin,8))"
  actions:
    merge:
      method: merge
